const express = require('express')
const router = express.Router()
const { requireAuth } = require('../middleware/auth')
const supabase = require('../lib/supabase')
const { sendCertificateEmail } = require('../lib/emails')

// Helper — issue certificate if eligible, return it (idempotent)
async function issueCertificate(student_id, course_id) {
  // Require 100% progress
  const { data: enrollment } = await supabase
    .from('enrollments')
    .select('progress_percent')
    .eq('student_id', student_id)
    .eq('course_id', course_id)
    .single()
  if (!enrollment || enrollment.progress_percent < 100) return null

  // If course has a quiz, require a passing attempt
  const { data: quiz } = await supabase
    .from('quizzes')
    .select('id')
    .eq('course_id', course_id)
    .maybeSingle()

  if (quiz) {
    const { data: pass } = await supabase
      .from('quiz_attempts')
      .select('id')
      .eq('quiz_id', quiz.id)
      .eq('student_id', student_id)
      .eq('passed', true)
      .maybeSingle()
    if (!pass) return null
  }

  // Upsert — cert_number auto-generated by DB default on first insert
  const { data: cert, error } = await supabase
    .from('certificates')
    .upsert({ student_id, course_id }, { onConflict: 'student_id,course_id' })
    .select('*, courses(title, thumbnail_url, users!courses_instructor_id_fkey(name)), users(name)')
    .single()
  if (error) throw error
  return cert
}

// Student: list my certificates
router.get('/my', requireAuth, async (req, res, next) => {
  try {
    const { data, error } = await supabase
      .from('certificates')
      .select('*, courses(title, thumbnail_url, users!courses_instructor_id_fkey(name))')
      .eq('student_id', req.user.id)
      .order('issued_at', { ascending: false })
    if (error) throw error
    res.json(data)
  } catch (err) { next(err) }
})

// Student: claim certificate after passing quiz (manual trigger from UI)
// Requires quiz passed; skips progress_percent check (column may not exist yet, quiz pass is sufficient)
router.post('/course/:courseId/claim', requireAuth, async (req, res, next) => {
  try {
    const student_id = req.user.id
    const course_id = req.params.courseId

    // Verify quiz exists and student passed it
    const { data: quiz } = await supabase
      .from('quizzes')
      .select('id')
      .eq('course_id', course_id)
      .maybeSingle()

    if (quiz) {
      const { data: pass } = await supabase
        .from('quiz_attempts')
        .select('id')
        .eq('quiz_id', quiz.id)
        .eq('student_id', student_id)
        .eq('passed', true)
        .maybeSingle()
      if (!pass) return res.status(400).json({ error: 'Pass the quiz first to earn this certificate' })
    } else {
      // No quiz — require enrollment to exist (must be enrolled)
      const { data: enrollment } = await supabase
        .from('enrollments')
        .select('id')
        .eq('student_id', student_id)
        .eq('course_id', course_id)
        .single()
      if (!enrollment) return res.status(400).json({ error: 'Not enrolled in this course' })
    }

    // Upsert certificate (idempotent)
    const { data: cert, error } = await supabase
      .from('certificates')
      .upsert({ student_id, course_id }, { onConflict: 'student_id,course_id' })
      .select('*, courses(title, thumbnail_url, users!courses_instructor_id_fkey(name)), users(name, email)')
      .single()
    if (error) throw error

    // Send certificate email (fire-and-forget)
    if (cert.users?.email && cert.courses?.title) {
      sendCertificateEmail({
        to: cert.users.email,
        studentName: cert.users.name || 'Student',
        courseTitle: cert.courses.title,
        certNumber: cert.cert_number,
      }).catch(() => {})
    }

    res.json(cert)
  } catch (err) { next(err) }
})

// Public: verify certificate by cert_number
router.get('/verify/:certNumber', async (req, res, next) => {
  try {
    const { data, error } = await supabase
      .from('certificates')
      .select('*, users(name), courses(title, users!courses_instructor_id_fkey(name))')
      .eq('cert_number', req.params.certNumber)
      .single()
    if (error || !data) return res.status(404).json({ error: 'Certificate not found' })
    res.json(data)
  } catch (err) { next(err) }
})

module.exports = router
module.exports.issueCertificate = issueCertificate
